---
- name: Create directories
  file:
    dest: '{{ item }}'
    state: directory
  with_items:
    - '{{ misc_dir }}'
    - ~/bin
    - ~/.vnc
    - ~/.config/i3

- name: Download blade
  git:
    repo: git@github.com:kz0817/blade.git
    dest: '{{ misc_dir }}/blade'
    accept_hostkey: yes

- name: Download dog
  git:
    repo: git@github.com:kz0817/dog.git
    dest: '{{ misc_dir }}/dog'
    accept_hostkey: yes

- name: Link dog.py
  file:
    src: '{{ misc_dir }}/dog/dog.py'
    dest: ~/bin/dog
    state: link

- name: Download qemu-cmd-gen.py
  git:
    repo: git@github.com:kz0817/qemu-helper.git
    dest: '{{ misc_dir }}/qemu-helper'
    accept_hostkey: yes

- name: Link qemu-helper
  file:
    src: '{{ misc_dir }}/qemu-helper/qemu-cmd-gen.py'
    dest: ~/bin/qemu-cmd-gen
    state: link

- name: Link diff-highlight
  file:
    src: '{{ misc_dir }}/blade/bin/diff-highlight'
    dest: ~/bin/diff-highlight
    state: link

- name: Check .bashrc is not link
  command: test -f ~/.bashrc -a ! -L .bashrc
  register: bashrc_is_not_link
  changed_when: bashrc_is_not_link.rc == 0
  failed_when: false

- name: Backup .bashrc if needed
  command: mv ~/.bashrc ~/.bashrc.orig
  when: bashrc_is_not_link.rc == 0

- name: Copy .bash_profile
  copy:
    src: files/bash_profile
    dest: ~/.bash_profile
    force: no

- name: Create .ssh/
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Create .ssh/config
  copy:
    src: files/ssh_config
    dest: ~/.ssh/config
    force: no

- name: Link filesr on the home directory
  file:
    src: '{{ blade_dir }}/home_conf/{{ item }}'
    dest: ~/{{ item }}
    state: link
  with_items:
    - .vimrc
    - .screenrc
    - .gdbinit
    - .gitconfig
    - .bashrc
    - .Xdefaults
    - .vnc/xstartup
    - .config/i3/config
