---
- name: Install packages for Debian
  apt:
    name:
      - sudo
      - git
      - procps
      - openssh-server
      - curl
      - screen
      - make
      - gnupg
      - vim
      - vim-fugitive
    update_cache: yes

- name: Install Desktop packages for Debian
  apt:
    name:
      - i3
      - tint2
      - stterm
      - autocutsel
      - picom
      - pcmanfm
      - fcitx5-mozc
      - firefox-esr
      - papirus-icon-theme
      - greybird-gtk-theme
      - gnome-screenshot
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - never
    - desktop
