---
- name: Add a group
  group:
    name: '{{ groupname }}'
    gid: '{{ gid }}'

- name: Add a user
  user:
    name: '{{ username }}'
    uid: '{{ uid }}'
    group: '{{ groupname }}'
    shell: /bin/bash

- name: Create ~/.ssh
  file:
    path: '/home/{{ username }}/.ssh'
    state: directory
    mode: '0700'
    owner: '{{ username }}'
    group: '{{ groupname }}'

- name: Copy SSH public keys
  copy:
    src: ~/.ssh/authorized_keys
    dest: '/home/{{ username }}/.ssh/authorized_keys'
    owner: '{{ username }}'
    group: '{{ groupname }}'
    backup: yes
  when: copy_ssh_auth_key

- name: Download SSH public keys from Github
  get_url:
    url: https://github.com/{{ github_name_for_ssh_auth_key }}.keys
    dest: '/home/{{ username }}/.ssh/authorized_keys'
    owner: '{{ username }}'
    group: '{{ groupname }}'
    backup: yes
  when: github_name_for_ssh_auth_key is defined

- name: Setting for sudoer
  copy:
    content: '{{ username }} ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: '/etc/sudoers.d/{{ username }}-nopasswd'

