#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Enable Intel Iris Pro" {
    insmod part_gpt
    insmod fat
    search --no-floppy --set=root --file /EFI/custom/apple_set_os.efi
    chainloader /EFI/custom/apple_set_os.efi
}
