- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_distribution }}
    - group_by: key=create_user
      when: user is defined
    - debug: msg="Distro {{ ansible_distribution }}"

- hosts: os_Ubuntu
  gather_facts: False
  tasks:
    - name: "install git (apt)"
      apt: name=git

    - name: "install ansible (apt)"
      apt: name=ansible


- hosts: os_CentOS
  gather_facts: False
  tasks:
    - name: "install epel-release (yum)"
      yum: name=epel-release

    - name: "install git (yum)"
      yum: name=git

    - name: "install vim (yum)"
      yum: name=vim

    - name: "install ansible (yum)"
      yum: name=ansible

    - name: "install sudo (yum)"
      yum: name=sudo

    - name: "install libselinux-python (yum)"
      yum: name=libselinux-python

    # We ignore the result for the machine w/o selinux.
    - selinux: state=disabled
      ignore_errors: True


- hosts: os_Alpine
  gather_facts: False
  tasks:
    - name: "install ansible (apk)"
      apk: name=ansible

    - name: "install git (apk)"
      apk: name=git


- hosts: create_user
  gather_facts: False
  tasks:
    - name: "add a user"
      user: name={{ user }} append=yes shell=/bin/bash

    - name: "ownership of home dir"
      file: owner={{ user }} path=/home/{{ user }} group={{ user }}

    - name: "mkdir ~/.ssh"
      file: path=/home/{{ user }}/.ssh state=directory mode=0700 owner={{ user }} group={{ user }}

    - name: "copy public key"
      copy: src=~/.ssh/id_rsa.pub dest=/home/{{ user }}/.ssh/authorized_keys owner={{ user }} group={{ user }}

    - name: "setting for sudoer"
      copy: content="{{ user }} ALL=(ALL:ALL) NOPASSWD:ALL" dest=/etc/sudoers.d/{{ user }}-nopasswd


