- hosts: all
  vars:
    misc_dir: "misc"
  tasks:
    - name: "mkdir misc"
      file: dest={{ misc_dir }} state=directory

    - name: "download priv-misc"
      git: repo=git@github.com:kz0817/priv-misc.git
           dest=misc/priv-misc
           accept_hostkey=yes

    - name: "link .vimrc"
      file: src=misc/priv-misc/home_conf/.vimrc dest=.vimrc state=link

    - name: "link .screenrc"
      file: src=misc/priv-misc/home_conf/.screenrc dest=.screenrc state=link

    - name: "link .gdbinit"
      file: src=misc/priv-misc/home_conf/.gdbinit dest=.gdbinit state=link

    - name: "link .gitconfig"
      file: src=misc/priv-misc/home_conf/.gitconfig dest=.gitconfig state=link

    - name: "check .bashrc is not link"
      command: test -f .bashrc -a ! -L .bashrc
      register: result
      ignore_errors: True

    - name: "backup .bashrc if needed"
      command: mv .bashrc .bashrc.orig
      when: result|success

    - name: "link .bashrc"
      file: src=misc/priv-misc/home_conf/.bashrc dest=.bashrc state=link

