- hosts: all
  vars:
    misc_dir: "~/misc"
  tasks:
    - name: "mkdir misc"
      file: dest={{ misc_dir }} state=directory

    - name: "download priv-misc"
      git:
        repo: git@github.com:kz0817/priv-misc.git
        dest: misc/priv-misc
        accept_hostkey: yes

    - name: "link .vimrc"
      file: src=misc/priv-misc/home_conf/.vimrc dest=~/.vimrc state=link

    - name: "link .screenrc"
      file: src=misc/priv-misc/home_conf/.screenrc dest=~/.screenrc state=link

    - name: "link .gdbinit"
      file: src=misc/priv-misc/home_conf/.gdbinit dest=~/.gdbinit state=link

    - name: "link .gitconfig (CentOS6)"
      file: src=misc/priv-misc/home_conf/.gitconfig dest=~/.gitconfig state=link
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

    - name: "link .gitconfig (Non CentOS6)"
      file: src=misc/priv-misc/home_conf/.gitconfig.cent6 dest=~/.gitconfig state=link
      when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

    - name: "check .bashrc is not link"
      command: test -f ~/.bashrc -a ! -L .bashrc
      register: bashrc_should_link
      failed_when: False

    - name: "backup .bashrc if needed"
      command: mv ~/.bashrc ~/.bashrc.orig
      when: bashrc_should_link.rc == 0

    - name: "link .bashrc"
      file: src=misc/priv-misc/home_conf/.bashrc dest=~/.bashrc state=link

    - name: "copy .bash_profile"
      copy: src=files/bash_profile dest=~/.bash_profile force=no

    - name: "mkdir .vnc/"
      file:
        path: ~/.vnc
        state: directory

    - name: "link .vnc/xstartup"
      file:
        src: "{{ misc_dir }}/priv-misc/home_conf/.vnc/xstartup"
        dest: ~/.vnc/xstartup
        state: link

    - name: "mkdir .config/i3"
      file:
        path: ~/.config/i3
        state: directory

    - name: "link .config/i3/config"
      file:
        src: "{{ misc_dir }}/priv-misc/home_conf/.config/i3/config"
        dest: ~/.config/i3/config
        state: link

