#!/bin/sh

export DefaultImModule=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

unset STY
xsetroot -solid SlateGray
autocutsel -s CLIPBOARD  &
autocutsel -s PRIMARY &
urxvt &
fcitx &

POST_XSTARTUP=~/.vnc/post-xstartup

if [ -e $POST_XSTARTUP ]; then
  . $POST_XSTARTUP
else
  jwm &
fi
